client_id: "MySQL_DB_consumer"
broker_ip: "155.185.4.4"
broker_port: 7883
account_topic_prefix: "/iot/user/unimore-fum-lab/edge/systems"
username: "unimore-fum-lab"
password: "wxugudolcbjttoke"
interval_s: 1
timeout_s: 10
topic_list: ['production/cycle/signals/start_stop_cycle/control',
             'production/cycle/signals/done_bags/telemetry',
             'production/cycle/signals/total_bags/control',
             'production/cycle/signals/placed_objects/telemetry',
             'production/cycle/time/telemetry',
             'production/cycle/signals/current_object/telemetry',
             'production/cycle/recipes/selected_recipe/control',
             'production/cycle/recipes/objects_types/control',
             'production/cycle/recipes/end_effector_indexes/control',
             'production/cycle/recipes/object_types_box_positions/control',
             'production/cycle/recipes/object_types_numbers/control',
             'cobot/states/cobot_state_cycle/telemetry',
             'cobot/states/robot_mode/telemetry',
             'cobot/states/power_on_robot/telemetry',
             'cobot/states/safety/telemetry',
             'cobot/joints/sensors/angles/telemetry',
             'cobot/joints/sensors/velocities/telemetry',
             'cobot/joints/sensors/current_consumptions/telemetry',
             'cobot/joints/sensors/temperatures/telemetry',
             'cobot/states/tcp/telemetry',
             'ai_on_edge/inference/6d_pose_estimation/control/response',
             'ai_on_edge/inference/scores/confidence/telemetry',
             'ai_on_edge/inference/scores/cosine_similarity/telemetry',
             'ai_on_edge/inference/time/telemetry']