client_id: "MySQL_DB_consumer"
broker_ip: "155.185.4.4"
broker_port: 7883
account_topic_prefix: "/iot/user/unimore-fum-lab/edge/systems"
username: "unimore-fum-lab"
password: "wxugudolcbjttoke"
interval_s: 1
timeout_s: 10
topic_list: ['production/cycle/signals/start_stop_cycle',
             'production/cycle/signals/done_bags',
             'production/cycle/signals/done_bag',
             'production/cycle/signals/total_bags',
             'production/cycle/signals/placed_objects',
             'production/cycle/signals/actual_done_bags',
             'production/cycle/signals/actual_placed_objects',
             'production/cycle/signals/actual_lost_objects',
             'production/cycle/time',
             'production/cycle/signals/current_object',
             'production/cycle/recipes/selected_recipe',
             'production/cycle/recipes/objects_types',
             'production/cycle/recipes/end_effector_indexes',
             'production/cycle/recipes/object_types_box_positions',
             'production/cycle/recipes/object_types_numbers',
             'cobot/states/cobot_state_cycle',
             'cobot/states/robot_mode',
             'cobot/states/power_on_robot',
             'cobot/states/safety',
             'cobot/states/alarm_counter',
             'cobot/joints/sensors/angles',
             'cobot/joints/sensors/velocities',
             'cobot/joints/sensors/current_consumptions',
             'cobot/joints/sensors/temperatures',
             'cobot/states/tcp',
             'ai_on_edge/inference/6d_pose_estimation',
             'ai_on_edge/inference/6d_pose_estimation',
             'ai_on_edge/inference/scores/confidence',
             'ai_on_edge/inference/scores/cosine_similarity',
             'ai_on_edge/inference/time',
             'ai_on_edge/image/rgb_image',
             'ai_on_edge/image/detection_image',
             'ai_on_edge/image/6d_pose_estimation_image',
             'ai_on_edge/image/picking_point_image']
