systems:
  system1:
    pick_and_place_id: "pnp_unimore_fum_lab"
    endpoint: "/pnp_unimore_fum_lab"

  system2:
    pick_and_place_id: "pnp_unimore_hipert_lab"
    endpoint: "/pnp_unimore_hipert_lab"

  system3:
    pick_and_place_id: "pnp_unimore_arscontrol_lab"
    endpoint: "/pnp_unimore_arscontrol_lab"